// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    DisplayList: typeof import('./pages/img-tool/components/DisplayList/index.vue')['default']
    HeaderLink: typeof import('./components/HeaderLink/index.vue')['default']
    ImgTool: typeof import('./pages/img-tool/index.vue')['default']
    Preview: typeof import('./pages/img-tool/components/Preview/index.vue')['default']
    PreviewList: typeof import('./pages/img-tool/components/PreviewList/index.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./pages/img-tool/components/Toolbar/index.vue')['default']
    VideoTool: typeof import('./pages/video-tool/index.vue')['default']
  }
}
